apiVersion : apps/v1
kind: Deployment
metadata:
  name: "rggetingedemo001-ea46"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "rggetingedemo001-ea46"
  template:
    metadata:
      labels:
        app: "rggetingedemo001-ea46"
    spec:
      containers:
        - name: "rggetingedemo001-ea46"
          image: "acrgetingedemo001.azurecr.io/rggetingedemo001"
          ports:
          - containerPort: 80