apiVersion : apps/v1
kind: Deployment
metadata:
  name: "rggetingedemo001-fac7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "rggetingedemo001-fac7"
  template:
    metadata:
      labels:
        app: "rggetingedemo001-fac7"
    spec:
      containers:
        - name: "rggetingedemo001-fac7"
          image: "arcgetingedemo001.azurecr.io/rggetingedemo001"
          ports:
          - containerPort: 80