apiVersion: v1
kind: Service
metadata:
    name: "rggetingedemo001-ea46"
    labels:
        app: "rggetingedemo001-ea46"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "rggetingedemo001-ea46"